/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kontaktlista;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author shaot01
 */
public class KontaktListaJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KontaktListaJFrame.class.getName());
 DbManager db = new DbManager();

    /**
     * Creates new form KontaktListaJFrame
     */
    public KontaktListaJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tbxFörnamn = new javax.swing.JTextField();
        rbtnFörnamn = new javax.swing.JRadioButton();
        rbtnEfternamn = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        tbxEfternamn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLista = new javax.swing.JTextArea();
        tbxTelefonnummer = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Förnamn");

        tbxFörnamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxFörnamnActionPerformed(evt);
            }
        });

        rbtnGroup.add(rbtnFörnamn);
        rbtnFörnamn.setSelected(true);
        rbtnFörnamn.setText("Förnamn först");
        rbtnFörnamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFörnamnActionPerformed(evt);
            }
        });

        rbtnGroup.add(rbtnEfternamn);
        rbtnEfternamn.setText("Efternamn först");

        jLabel2.setText("Efternamn");

        tbxEfternamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxEfternamnActionPerformed(evt);
            }
        });

        jLabel3.setText("Telefon");

        jButton1.setText("Lägg Till");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtLista.setColumns(20);
        txtLista.setRows(5);
        jScrollPane1.setViewportView(txtLista);

        tbxTelefonnummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxTelefonnummerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbxFörnamn, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(tbxTelefonnummer))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tbxEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtnFörnamn)
                                .addGap(34, 34, 34)
                                .addComponent(rbtnEfternamn)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tbxFörnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tbxEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1)
                    .addComponent(tbxTelefonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnFörnamn)
                    .addComponent(rbtnEfternamn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String förnamn = this.tbxFörnamn.getText(); //läser av textboxen
        this.tbxFörnamn.setText(""); //Tömmer textboxen
        System.out.println(förnamn);
        
        String efternamn = this.tbxEfternamn.getText();//Skriver ut texten konsollen
        this.tbxEfternamn.setText("");
        
        String telefonnummer = this.tbxTelefonnummer.getText();
        this.tbxTelefonnummer.setText("");
        
        if(förnamn.isBlank()&&efternamn.isBlank()&&telefonnummer.isBlank()) {
            //Kollar om det finns text, annars skapas inte kontakten
        } 
        else{
            
            Kontakt kon = new Kontakt(förnamn,efternamn,telefonnummer);
            db.insert(kon);
         
         if(this.rbtnFörnamn.isSelected()) {
             SkrivUtF();
         }
         else {
             SkrivUtE();
         } 
             
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbxTelefonnummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxTelefonnummerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxTelefonnummerActionPerformed

    private void tbxEfternamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxEfternamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxEfternamnActionPerformed

    private void tbxFörnamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxFörnamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxFörnamnActionPerformed

    private void rbtnFörnamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFörnamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnFörnamnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KontaktListaJFrame().setVisible(true));
    }
    
    private void SkrivUtF(){
        ResultSet rs = db.getAllData();
        if (rs != null) {
            try {
                while (rs.next()) {
                    this.txtLista.append (rs.getInt("kontaktid") + "\t"
                            + rs.getString("firstname") + "\t "
                            + rs.getString("lastname") + "\t "
                            + rs.getString("phonenumber") + "\n");
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        } else {
            System.out.println("Ingen data från databasen, kontrollera anslutningen.");
        }

    }
    
    
    private void SkrivUtE(){
              ResultSet rs = db.getAllData();
        if (rs != null) {
            try {
                while (rs.next()) {
                    this.txtLista.append (rs.getInt("kontaktid") + "\t"
                            + rs.getString("firstname") + "\t "
                            + rs.getString("lastname") + "\t "
                            + rs.getString("phonenumber") + "\n); "
                            + rs.getInt("age"));
                }
            } catch (SQLException ex) {
                System.out.println("Ingen data.");
            }
        } else {
            System.out.println("Ingen data från databasen, kontrollera anslutningen.");
        }
  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnEfternamn;
    private javax.swing.JRadioButton rbtnFörnamn;
    private javax.swing.ButtonGroup rbtnGroup;
    private javax.swing.JTextField tbxEfternamn;
    private javax.swing.JTextField tbxFörnamn;
    private javax.swing.JTextField tbxTelefonnummer;
    private javax.swing.JTextArea txtLista;
    // End of variables declaration//GEN-END:variables

   
}
